import type { Metadata } from "next";
import "./globals.css";
import { Providers } from "./lib/Providers";

export const metadata: Metadata = {
  title: "Shopno Mela",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" data-theme="light">
      <body className={`antialiased`}>
        <Providers>
          <div className="mx-auto">{children}</div>
        </Providers>
      </body>
    </html>
  );
}
