import type { Metadata } from "next";
import "./globals.css";
import { Providers } from "./lib/Providers";
import Navbar from "./(commonLayout)/components/shared/Navbar";
import Footer from "./(commonLayout)/components/shared/Footer";

export const metadata: Metadata = {
  title: "Pet Bhandar",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" data-theme="light">
      <body className={`antialiased`}>
        <Providers>
          <Navbar />
          <div className="mx-auto">{children}</div>
          <Footer />
        </Providers>
      </body>
    </html>
  );
}
