import type { Metadata } from "next";

export const metadata: Metadata = {
  title: "Shopno Mela",
  description: "Generated by create next app",
};

export default function AdminDashboardLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <div>
      <h1>Admin dashboard layout</h1>
      {children}
    </div>
  );
}
