import type { Metadata } from "next";
import Footer from "./components/shared/Footer";
import Navbar from "./components/shared/Navbar";

export const metadata: Metadata = {
  title: "Pet Bhandar",
  description: "Generated by create next app",
};

export default function commonLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <div>
      <Navbar />
      <div className="mx-auto">{children}</div>
      <Footer />
    </div>
  );
}
